language: java

jdk:
  - oraclejdk8

notifications:
  email:
    - ozwolf@gmail.com

env:
  global:
    - GPG_DIR="`pwd`/gpg"
    - secure: BNxtYo5SzGaBD11sojd7GesFgbS+qBtyqnpkF8WXjnaOH3uMQQibk11+MFpafBYt1A4IKHX6IldjA/Wswm9l0jbYBAYPyLtsWR5DOlItA9DS1El5ty0I2/Vl7sLKnH9UCnmt95xFcXwxC44CYiALEdRBdb6QOBnh+9X/s/i6z14=
    - secure: SM5aTnwKO7k+YwupO8UM7b05zEQRvJBp+KWWDQYhzErFYsLnU9WHAIFTL1nSz5XxwB+yBwq7kt5aQjI08CL+BzUrbNtCM4Yiw1asitObPCWAAvxAvt5mbOgs50zdZ3hGjSFLR1NXdy2CXpqThDx9qba3Oifb29LIzdygg9yz6PA=
    - secure: bpLGJDOIaEkZgKeg7b8J97E0ApG2oigPxOF7HXQY6ilRxaGlE/lT35/dUXIv5xuf3AQ3PpnlHEq0X1f6GVn4FtRA9KXLyJftkDXHxg+/CO1Wk8DxsNiW/geJlKwBxMVYCB8XZewqOBMeF3XQWYwMZ2AZ5Qi8K2RyiapVntNY520=
    - secure: iLf6Uf4hBfmMsBq+hFzAyohlwiJwEvCla0QB+HUoPC2SCAbIias0MqxwmhwvYMKgiavcXbJvqn92kDpOYFI36hL1yQzf8uPmvJ20yY5jVSZjJ0Saj9dXLLmAZ0dXgrAgvbN4nzTfWM/7mGITGGM0fh0PKKucAj/UrzBNxoBwn2s=
    - secure: AwN9DuEA1N36hnXT5BlXXcMJN1dKrIg335lw/Pl98d84rY8T+9dMCf9Hfrx952W3cfAHhZ3YNIchPx+B5q0e026BDZnQDBkKvpoxNB3o+4HgLdqeNy0/dfOuD1/gOs4KDYLFuESzev7Hvj4h7hEoAve44mT3639t0kk9fTu+krs=
    - secure: PyW4dntH7ectARI6+/AIjvpHSOA+h5tmCFl4OJQc20ONa8BC63KIY6JibAgZMupll4HKH+Ylr5PFdkzdDq9zvJBlecfpOWszjr8AYRNwRVZqR5MDpusMh86wGxbaRHiFtrslvYx6EbasglgitQjfLiMXz7zFZBpc9qXWpXRYPxs=

before_script:
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/pubring.gpg.enc -out $GPG_DIR/pubring.gpg -d
  - openssl aes-256-cbc -pass pass:$ENCRYPTION_PASSWORD -in $GPG_DIR/secring.gpg.enc -out $GPG_DIR/secring.gpg -d

script:
  - mvn -P ossrh clean source:jar deploy --settings travis-settings.xml
